services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000" # Maps Django's dev server to localhost:8000
    volumes:
      - ./backend:/app # Sync code changes in backend to the container
      - ./backend/firebase_auth:/firebase_auth  # Mount the whole firebase_auth directory

    env_file:
      - .env # Specifies the path to your .env file

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # Specify the development Dockerfile for the frontend
    ports:
      - "3000:3000" # Maps Next.js to localhost:3000
    volumes:
      - ./frontend:/app # Sync code changes in frontend to the container
      - /app/node_modules  # 👈 Add this line

    working_dir: /app  
    environment:
      - NODE_ENV=development
    depends_on:
      - backend # Ensure the backend is ready before starting
    env_file:
      - .env # Specifies the path to your .env file