# Generated by Django 4.2.8 on 2023-12-12 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(upload_to='profile_photos/')),
                ('profile_font', models.CharField(default='sans-serif', max_length=255)),
                ('profile_font_color', models.CharField(default='#000000', max_length=7)),
                ('background_flag', models.CharField(choices=[('color', 'Color'), ('image', 'Image')], max_length=10)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='profile_backgrounds/')),
                ('link_bubble', models.CharField(choices=[('bubble_style_1', 'Bubble Style 1'), ('bubble_style_2', 'Bubble Style 2')], max_length=20)),
                ('link_font', models.CharField(default='sans-serif', max_length=255)),
                ('social_media_icons_location', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='bottom', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'Linked In'), ('youtube', 'Youtube')], max_length=20)),
                ('link', models.URLField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_profiles', to='linklists.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='link_photos/')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='linklists.list')),
            ],
        ),
    ]
