# Generated by Django 4.2.8 on 2024-08-12 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_photo_url', models.URLField(null=True)),
                ('profile_font', models.CharField(default='sans-serif', max_length=255)),
                ('profile_font_color', models.CharField(default='#000000', max_length=7)),
                ('background_flag', models.CharField(choices=[('color', 'Color'), ('image', 'Image')], max_length=10)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('background_image_url', models.URLField(null=True)),
                ('link_bubble_style', models.CharField(choices=[('bubble_style_1', 'Bubble Style 1'), ('bubble_style_2', 'Bubble Style 2'), ('bubble_filled', 'Bubble Filled'), ('bubble_filled_rounded', 'Bubble Filled Rounded'), ('bubble_filled_circular', 'Bubble Filled Circular'), ('bubble_outline', 'Bubble Outline'), ('bubble_outline_rounded', 'Bubble Outline Rounded'), ('bubble_outline_circular', 'Bubble Outline Circular'), ('bubble_shadow', 'Bubble Shadow'), ('bubble_shadow_rounded', 'Bubble Shadow Rounded'), ('bubble_shadow_circular', 'Bubble Shadow Circular')], max_length=30)),
                ('link_bubble_color', models.CharField(default='#000000', max_length=7)),
                ('link_font', models.CharField(default='sans-serif', max_length=255)),
                ('link_font_color', models.CharField(default='#000000', max_length=7)),
                ('social_media_icons_location', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='bottom', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'Youtube')], max_length=20)),
                ('link', models.URLField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_profiles', to='linklists.list')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('link_photo_url', models.URLField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='linklists.list')),
            ],
        ),
    ]
