# Generated by Django 4.2.8 on 2023-12-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'Youtube')], max_length=20),
        ),
    ]
