# Generated by Django 4.2.8 on 2025-01-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['user'], name='linklists_l_user_id_72d1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['username'], name='linklists_l_usernam_1529f9_idx'),
        ),
    ]
