# Generated by Django 4.2.8 on 2023-12-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0002_alter_list_bio_alter_socialmedia_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='link_bubble',
            new_name='link_bubble_style',
        ),
    ]
