# Generated by Django 4.2.8 on 2024-09-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0003_alter_list_background_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='background_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
