# Generated by Django 4.2.8 on 2024-01-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0003_rename_link_bubble_list_link_bubble_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='user',
        ),
    ]
