# Generated by Django 4.2.8 on 2024-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0004_remove_socialmedia_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='link_bubble_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='list',
            name='link_font_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='list',
            name='link_bubble_style',
            field=models.CharField(choices=[('bubble_style_1', 'Bubble Style 1'), ('bubble_style_2', 'Bubble Style 2'), ('bubble_filled', 'Bubble Filled'), ('bubble_filled_rounded', 'Bubble Filled Rounded'), ('bubble_filled_circular', 'Bubble Filled Circular'), ('bubble_outline', 'Bubble Outline'), ('bubble_outline_rounded', 'Bubble Outline Rounded'), ('bubble_outline_circular', 'Bubble Outline Circular'), ('bubble_shadow', 'Bubble Shadow'), ('bubble_shadow_rounded', 'Bubble Shadow Rounded'), ('bubble_shadow_circular', 'Bubble Shadow Circular')], max_length=30),
        ),
    ]
