# Generated by Django 4.2.8 on 2024-02-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0005_list_link_bubble_color_list_link_font_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
