# Generated by Django 4.2.8 on 2024-09-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0006_alter_link_user_alter_socialmedia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='link_bubble_style',
            field=models.CharField(choices=[('bubble_style_1', 'Bubble Style 1'), ('bubble_style_2', 'Bubble Style 2'), ('bubble_filled', 'Bubble Filled'), ('bubble_filled_rounded', 'Bubble Filled Rounded'), ('bubble_filled_circular', 'Bubble Filled Circular'), ('bubble_outline', 'Bubble Outline'), ('bubble_outline_rounded', 'Bubble Outline Rounded'), ('bubble_outline_circular', 'Bubble Outline Circular'), ('bubble_shadow', 'Bubble Shadow'), ('bubble_shadow_rounded', 'Bubble Shadow Rounded'), ('bubble_shadow_circular', 'Bubble Shadow Circular')], default='bubble_outline', max_length=30),
        ),
    ]
