# Generated by Django 4.2.8 on 2024-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0006_link_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='list',
            name='photo',
        ),
        migrations.AddField(
            model_name='link',
            name='link_photo_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='profile_photo_url',
            field=models.URLField(null=True),
        ),
    ]
