# Generated by Django 4.2.8 on 2024-04-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0007_remove_link_photo_remove_list_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='background_image',
        ),
        migrations.AddField(
            model_name='list',
            name='background_image_url',
            field=models.URLField(null=True),
        ),
    ]
