# Generated by Django 4.2.8 on 2024-09-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0007_alter_list_link_bubble_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
