# Generated by Django 4.2.8 on 2024-10-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0008_alter_link_link_alter_socialmedia_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='profile_font',
            field=models.CharField(default='roboto', max_length=255),
        ),
    ]
