# Generated by Django 4.2.8 on 2024-04-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0008_remove_list_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'Youtube')], max_length=20),
        ),
    ]
