# Generated by Django 4.2.8 on 2024-10-10 16:59

from django.db import migrations, models
import linklists.validators


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0009_alter_list_profile_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='username',
            field=models.CharField(default='user', max_length=255, unique=True, validators=[linklists.validators.validate_username]),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
