# Generated by Django 4.2.8 on 2024-10-10 16:59

from django.db import migrations, models
import linklists.validators


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0010_list_username_alter_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[linklists.validators.validate_username]),
        ),
    ]
