# Generated by Django 4.2.8 on 2024-11-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linklists', '0011_alter_list_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('social_media_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linklists.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linklists.list')),
            ],
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linklists.link')),
            ],
        ),
    ]
