import type { Metadata } from 'next'
import './globals.css'
import { AuthProvider } from '@/utils/AuthContext'

export const metadata: Metadata = {
  title: 'Linknbio: Share your links in one place',
  description: 'Generated by create next app',
} 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
